problems:
  resource: "Condition"
  resource_template: "cda/condition"
  entry_template: "cda/cda_problem_entry"
  section_template_id: "2.16.840.1.113883.10.20.1.11"
  code: "11450-4"
  display: "Problem List"
  entry_act_template_ids:
    - "2.16.840.1.113883.10.20.1.27"
    - "1.3.6.1.4.1.19376.1.5.3.1.4.5.1"
    - "1.3.6.1.4.1.19376.1.5.3.1.4.5.2"
    - "2.16.840.1.113883.3.88.11.32.7"
    - "2.16.840.1.113883.3.88.11.83.7"
  entry_act_entryRelationship_observation_template_ids:
    - "1.3.6.1.4.1.19376.1.5.3.1.4.5"
    - "2.16.840.1.113883.10.20.1.28"
  # New configurable options
  act_status_code: "active"
  entry_relationship_type_code: "SUBJ"
  entry_relationship_inversion_ind: false
  observation_code: "55607006"
  observation_code_system: "2.16.840.1.113883.6.96"
  observation_code_system_name: "SNOMED CT"
  observation_display_name: "Problem"
  observation_status_code: "completed"
  status_loinc_code: "33999-4"
  status_code_system: "2.16.840.1.113883.6.1"
  status_display_name: "Status"
  status_observation_status_code: "completed"

medications:
  resource: "MedicationStatement"
  resource_template: "cda/medication_statement"
  entry_template: "cda/cda_medication_entry"
  section_template_id: "2.16.840.1.113883.10.20.1.8"
  code: "10160-0"
  display: "Medications"
  entry_act_template_ids:
    - "2.16.840.1.113883.10.20.1.24"
    - "2.16.840.1.113883.3.88.11.83.8"
    - "1.3.6.1.4.1.19376.1.5.3.1.4.7"
    - "1.3.6.1.4.1.19376.1.5.3.1.4.7.1"
    - "2.16.840.1.113883.3.88.11.32.8"
  # New configurable options
  act_status_code: "active"
  entry_relationship_type_code: "SUBJ"
  entry_relationship_inversion_ind: false
  observation_code: "10160-0"
  observation_code_system: "2.16.840.1.113883.6.1"
  observation_code_system_name: "LOINC"
  observation_display_name: "Medication"
  observation_status_code: "completed"
  status_code_system: "2.16.840.1.113883.6.1"
  status_display_name: "Status"
  status_observation_status_code: "completed"

allergies:
  resource: "AllergyIntolerance"
  resource_template: "cda/allergy_intolerance"
  entry_template: "cda/cda_allergy_entry"
  section_template_id: "2.16.840.1.113883.10.20.1.2"
  code: "48765-2"
  display: "Allergies"
  entry_act_template_ids:
    - "1.3.6.1.4.1.19376.1.5.3.1.4.5.1"
    - "1.3.6.1.4.1.19376.1.5.3.1.4.5.3"
    - "2.16.840.1.113883.3.88.11.32.6"
    - "2.16.840.1.113883.3.88.11.83.6"
  # New configurable options
  act_status_code: "active"
  entry_relationship_type_code: "SUBJ"
  entry_relationship_inversion_ind: false
  observation_code: "48765-2"
  observation_code_system: "2.16.840.1.113883.6.1"
  observation_code_system_name: "LOINC"
  observation_display_name: "Allergy"
  observation_status_code: "completed"
  status_code_system: "2.16.840.1.113883.6.1"
  status_display_name: "Status"
  status_observation_status_code: "completed"
