# CDA to FHIR section definitions
sections:
  problems:
    template: cda/problem.liquid
    template_id: "2.16.840.1.113883.10.20.1.11"
    code: "11450-4"
    resource: "Condition"
    status_loinc_code: "33999-4"

  medications:
    template: cda/medication.liquid
    template_id: "2.16.840.1.113883.10.20.1.8"
    code: "10160-0"
    resource: "MedicationStatement"

  allergies:
    template: cda/allergy.liquid
    template_id: "2.16.840.1.113883.10.20.1.2"
    code: "48765-2"
    resource: "AllergyIntolerance"

  notes:
    template: cda/note.liquid
    template_id: "1.2.840.114350.1.72.1.200001"
    code: "51847-2"
    resource: "DocumentReference"
