# Allergies Section Configuration
# This file contains configuration for the allergies section
# TODO: Implement

# Basic section information
resource: "AllergyIntolerance"
resource_template: "cda/allergy_intolerance"
entry_template: "cda/cda_allergy_entry"
section_template_id: "2.16.840.1.113883.10.20.1.2"
code: "48765-2"
display: "Allergies"

# Entry act template IDs
entry_act_template_ids:
  - "1.3.6.1.4.1.19376.1.5.3.1.4.5.1"
  - "1.3.6.1.4.1.19376.1.5.3.1.4.5.3"
  - "2.16.840.1.113883.3.88.11.32.6"
  - "2.16.840.1.113883.3.88.11.83.6"

# Status codes and other configurable options
act_status_code: "active"
entry_relationship_type_code: "SUBJ"
entry_relationship_inversion_ind: false
observation_code: "48765-2"
observation_code_system: "2.16.840.1.113883.6.1"
observation_code_system_name: "LOINC"
observation_display_name: "Allergy"
observation_status_code: "completed"
status_code_system: "2.16.840.1.113883.6.1"
status_display_name: "Status"
status_observation_status_code: "completed"

# Rendering configuration
rendering:
  narrative:
    include: true
    template: "narratives/allergy_narrative"
  entry:
    include_status: true
    include_reaction: true
    include_severity: true
    include_dates: true
