# Medications Section Configuration
# This file contains configuration for the medications section
# TODO: Implement

# Basic section information
resource: "MedicationStatement"
resource_template: "cda/medication_statement"
entry_template: "cda/cda_medication_entry"
section_template_id: "2.16.840.1.113883.10.20.1.8"
code: "10160-0"
display: "Medications"

# Entry act template IDs
entry_act_template_ids:
  - "2.16.840.1.113883.10.20.1.24"
  - "2.16.840.1.113883.3.88.11.83.8"
  - "1.3.6.1.4.1.19376.1.5.3.1.4.7"
  - "1.3.6.1.4.1.19376.1.5.3.1.4.7.1"
  - "2.16.840.1.113883.3.88.11.32.8"

# Status codes and other configurable options
act_status_code: "active"
entry_relationship_type_code: "SUBJ"
entry_relationship_inversion_ind: false
observation_code: "10160-0"
observation_code_system: "2.16.840.1.113883.6.1"
observation_code_system_name: "LOINC"
observation_display_name: "Medication"
observation_status_code: "completed"
status_code_system: "2.16.840.1.113883.6.1"
status_display_name: "Status"
status_observation_status_code: "completed"

# Rendering configuration
rendering:
  narrative:
    include: true
    template: "narratives/medication_narrative"
  entry:
    include_status: true
    include_dates: true
    include_dosage: true
    include_route: true
    include_frequency: true
