# Problems Section Configuration
# ========================

# Metadata for both extraction and rendering processes
resource: "Condition"
resource_template: "cda_fhir/condition"
entry_template: "fhir_cda/problem_entry"

# Section identifiers (used for extraction)
identifiers:
  template_id: "2.16.840.1.113883.10.20.1.11"
  code: "11450-4"
  code_system: "2.16.840.1.113883.6.1"
  code_system_name: "LOINC"
  display: "Problem List"
  clinical_status:
    template_id: "2.16.840.1.113883.10.20.1.47"
    code: "33999-4"

# Template configuration (used for rendering/generation)
template:
  # Act element configuration
  act:
    template_id:
      - "2.16.840.1.113883.10.20.1.27"
      - "1.3.6.1.4.1.19376.1.5.3.1.4.5.1"
      - "1.3.6.1.4.1.19376.1.5.3.1.4.5.2"
      - "2.16.840.1.113883.3.88.11.32.7"
      - "2.16.840.1.113883.3.88.11.83.7"
    status_code: "completed"

  # Problem observation configuration
  problem_obs:
    type_code: "SUBJ"
    inversion_ind: false
    template_id:
      - "1.3.6.1.4.1.19376.1.5.3.1.4.5"
      - "2.16.840.1.113883.10.20.1.28"
    code: "55607006"
    code_system: "2.16.840.1.113883.6.96"
    code_system_name: "SNOMED CT"
    display_name: "Problem"
    status_code: "completed"

  # Clinical status observation configuration
  clinical_status_obs:
    template_id: "2.16.840.1.113883.10.20.1.47"
    code: "33999-4"
    code_system: "2.16.840.1.113883.6.1"
    code_system_name: "LOINC"
    display_name: "Status"
    status_code: "completed"

# Rendering configuration (not used)
rendering:
  narrative:
    include: true
    template: "narratives/problem_narrative"
  entry:
    include_status: true
    include_dates: true
