# HealthChain Interoperability Engine Default Configuration
# This file contains default values used throughout the engine

# Default resource fields
defaults:
  # Common defaults for all resources
  common:
    id_prefix: "hc-"
    subject:
      reference: "Patient/example"

  # Resource-specific defaults
  resources:
    Condition:
      clinicalStatus:
        coding:
          - system: "http://terminology.hl7.org/CodeSystem/condition-clinical"
            code: "unknown"
            display: "Unknown"
      verificationStatus:
        coding:
          - system: "http://terminology.hl7.org/CodeSystem/condition-ver-status"
            code: "unconfirmed"
            display: "Unconfirmed"

    MedicationStatement:
      status: "unknown"
      effectiveDateTime: "{{ now | date: '%Y-%m-%d' }}"
      medicationCodeableConcept:
        coding:
          - system: "http://terminology.hl7.org/CodeSystem/v3-NullFlavor"
            code: "UNK"
            display: "Unknown"

    AllergyIntolerance:
      clinicalStatus:
        coding:
          - system: "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical"
            code: "unknown"
            display: "Unknown"
      verificationStatus:
        coding:
          - system: "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification"
            code: "unconfirmed"
            display: "Unconfirmed"
      type: "allergy"
      criticality: "low"

# Template names and paths
templates:
  # Core templates
  core:
    section: "cda_section"
    document: "cda_document"

  # Resource templates
  resources:
    condition: "cda/condition"
    medication_statement: "cda/medication_statement"
    allergy_intolerance: "cda/allergy_intolerance"

  # Entry templates
  entries:
    problem: "cda/cda_problem_entry"
    medication: "cda/cda_medication_entry"
    allergy: "cda/cda_allergy_entry"

# Format settings
formats:
  # Date and time formats
  date:
    timestamp: "%Y%m%d"
    datetime: "%Y-%m-%dT%H:%M:%SZ"
    date: "%Y-%m-%d"
    time: "%H:%M:%S"

  # ID and reference formats
  ids:
    resource: "hc-{uuid}"
    reference_name: "#{uuid}name"
    section: "section-{key}"

# Validation settings
validation:
  strict_mode: true
  warn_on_missing: true
  ignore_unknown_fields: true

# Parser settings
parser:
  max_entries: 1000
  skip_empty_sections: true

# Logging settings
logging:
  level: "INFO"
  include_timestamps: true

# Error handling
errors:
  retry_count: 3
  fail_on_critical: true

# Performance settings
performance:
  cache_templates: true
  cache_mappings: true
  batch_size: 100
