"""
Synthea dataset loader.

Loads synthetic patient data generated by Synthea.
"""

import logging
from pathlib import Path
from typing import Dict, List, Optional

from healthchain.sandbox.datasets import DatasetLoader

log = logging.getLogger(__name__)


class SyntheaLoader(DatasetLoader):
    """
    Loader for Synthea-generated FHIR data.

    Synthea is an open-source synthetic patient generator that produces
    realistic patient records in FHIR format. This loader supports loading
    Synthea-generated FHIR bundles.

    Examples:
        Load via SandboxClient:
        >>> client = SandboxClient(...)
        >>> client.load_from_registry(
        ...     "synthea",
        ...     data_dir="./data/synthea/output/fhir",
        ...     sample_size=10
        ... )
    """

    @property
    def name(self) -> str:
        """Dataset name for registration."""
        return "synthea"

    @property
    def description(self) -> str:
        """Dataset description."""
        return "Synthea: Synthetic patient data generated by SyntheaTM"

    def load(
        self,
        data_dir: str,
        patient_ids: Optional[List[str]] = None,
        sample_size: Optional[int] = None,
        random_seed: Optional[int] = None,
        **kwargs,
    ) -> Dict:
        """
        Load Synthea FHIR data as dict.

        Args:
            data_dir: Path to Synthea FHIR output directory
            patient_ids: Specific patient IDs to load
            sample_size: Number of random patients to sample
            random_seed: Random seed for reproducible sampling
            **kwargs: Additional parameters (reserved for future use)

        Returns:
            Dict containing FHIR resources

        Raises:
            FileNotFoundError: If data path doesn't exist
            NotImplementedError: Full implementation pending
        """
        data_dir = Path(data_dir)
        if not data_dir.exists():
            raise FileNotFoundError(
                f"Synthea data not found at: {data_dir}. "
                "Please provide a valid data_dir."
            )

        # TODO: Implement Synthea FHIR bundle loading
        # Synthea typically outputs individual FHIR bundles per patient
        # Format: <patient-id>.json containing a Bundle resource

        raise NotImplementedError(
            "Synthea loader is not yet fully implemented. "
            "This is a placeholder for future functionality. "
            "For now, please use load_free_text() with CdsDataGenerator for synthetic data."
        )
