# Medications Section Configuration
# This file contains configuration for the medications section
# TODO: Implement

# Basic section information
resource: "MedicationStatement"
resource_template: "cda/medication_statement"
entry_template: "cda/cda_medication_entry"
template_id: "2.16.840.1.113883.10.20.1.8"
code: "10160-0"
display: "Medications"

# Entry act template IDs
entry:
  substance_administration:
    status_code: "completed"
    template_ids:
      - "2.16.840.1.113883.10.20.1.24"
      - "2.16.840.1.113883.3.88.11.83.8"
      - "1.3.6.1.4.1.19376.1.5.3.1.4.7"
      - "1.3.6.1.4.1.19376.1.5.3.1.4.7.1"
      - "2.16.840.1.113883.3.88.11.32.8"

consumable:
  manufactured_product:
    template_ids:
      - "1.3.6.1.4.1.19376.1.5.3.1.4.7.2"
      - "2.16.840.1.113883.10.20.1.53"
      - "2.16.840.1.113883.3.88.11.32.9"
      - "2.16.840.1.113883.3.88.11.83.8.2"

clinical_status_observation:
  template_id:
    - "2.16.840.1.113883.10.20.1.47"
  status_code: "completed"
  code:
    code: "33999-4"
    code_system: "2.16.840.1.113883.6.1"
    code_system_name: "LOINC"
    display_name: "Status"
  value:
    code: "755561003"
    code_system: "2.16.840.1.113883.6.96"
    code_system_name: "SNOMED CT"
    display_name: "Active"


# Rendering configuration
rendering:
  narrative:
    include: true
    template: "narratives/medication_narrative"
  entry:
    include_status: true
    include_dates: true
    include_dosage: true
    include_route: true
    include_frequency: true
