# Problems Section Configuration
# This file contains configuration for the problems section

# Basic required section information
resource: "Condition"
resource_template: "cda/condition"
entry_template: "cda/cda_problem_entry"

template_id: "2.16.840.1.113883.10.20.1.11"
code: "11450-4"
display: "Problem List"

# Entry act template IDs
entry:
  act:
    template_ids:
      - "2.16.840.1.113883.10.20.1.27"
      - "1.3.6.1.4.1.19376.1.5.3.1.4.5.1"
      - "1.3.6.1.4.1.19376.1.5.3.1.4.5.2"
      - "2.16.840.1.113883.3.88.11.32.7"
      - "2.16.840.1.113883.3.88.11.83.7"
    status_code: "completed"

main_entry_relationship:
  type_code: "SUBJ"
  inversion_ind: false
  observation:
    code: "55607006"
    code_system: "2.16.840.1.113883.6.96"
    code_system_name: "SNOMED CT"
    display_name: "Problem"
    status_code: "completed"
    template_ids:
      - "1.3.6.1.4.1.19376.1.5.3.1.4.5"
      - "2.16.840.1.113883.10.20.1.28"

clinical_status_observation:
  code: "33999-4"
  code_system: "2.16.840.1.113883.6.1"
  code_system_name: "LOINC"
  display_name: "Status"
  status_code: "completed"

# Rendering configuration (not used yet)
rendering:
  narrative:
    include: true
    template: "narratives/problem_narrative"
  entry:
    include_status: true
    include_dates: true
